baseURL = "https://whynot.fail"
disablePathToLower = true
languageCode = "en-us"
title = "WhyNot.Fail"
paginate = 5
preserveTaxonomyNames = true
assetDir = "static"
enableRobotsTXT = true
metaDataFormat = "toml"

[author]
name = "Dimitris Zervas"

[markup.goldmark.renderer]
unsafe= true

[params]
slogan = "Why not fail?"
description = "Cause when you fail, somebody has to laugh at you"
plausible = "whynot.fail"
plausibleCustomDomain = "stats.whynot.fail"
#email = "dzervas@dzervas.gr"
copyright = [
    "Nederburg Hugo Theme by [Appernetic](https://appernetic.io).",
    "Supported by [Plausible](https://plausible.io)"
]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[[menu.main]]
identifier = "webring"
name = "Webring"
url = "https://webring.stavros.io/"
weight = 3

[[menu.main]]
parent = "webring"
name = "Previous"
url = "https://webring.stavros.io/prev"
weight = 1

[[menu.main]]
parent = "webring"
name = "Random"
url = "https://webring.stavros.io/random"
weight = 2

[[menu.main]]
parent = "webring"
name = "Next"
url = "https://webring.stavros.io/next"
weight = 3

[module]
    [[module.mounts]]
    source = "static"
    target = "static"

    [[module.mounts]]
    source = "node_modules/lunr/lunr.min.js"
    target = "static/vendor/lunr.min.js"

[params.social]
#email = "dzervas@dzervas.gr"
#twitter = "https://twitter.com/_dzervas"
github = "https://github.com/dzervas/whynot.fail"
rss = true

[params.social.utterances]
repo = "dzervas/whynot.fail"

[params.writers]
[params.writers.dzervas]
link = "https://dzervas.gr"
email = "dzervas@dzervas.gr"
bio = "Creator of this site and lover of fails."
twitter = "https://twitter.com/_dzervas"
github = "https://github.com/dzervas"

[outputFormats.SearchIndex]
basename = "search"
mediaType = "application/json"
isPlainText = true
notAlternative = true

[outputs]
home = ["HTML", "RSS", "SearchIndex"]
