baseURL = "https://whynot.fail"
disablePathToLower = true
languageCode = "en-us"
title = "WhyNot.Fail"
theme = "hugo-nederburg-theme"
paginate = 5
preserveTaxonomyNames = true
assetDir = "static"

[author]
name = "Dimitris Zervas"

[params]
slogan = "Why not fail?"
description = "Cause when you fail, somebody has to laugh at you"
plausible = true
#email = "dzervas@dzervas.gr"
copyright = [
    "Nederburg Hugo Theme by [Appernetic](https://appernetic.io).",
    "Supported by [Plausible](https://plausible.io)"
]

[[menu.main]]
name = "Home"
url = "/"
weight = 2

[[menu.main]]
name = "About"
url = "about/"
weight = 3

[[menu.main]]
identifier = "webring"
name = "Tech Makers Webring"
url = "https://webring.stavros.io/"
weight = 1

[[menu.main]]
parent = "webring"
name = "Previous"
url = "https://webring.stavros.io/prev"
weight = 1

[[menu.main]]
parent = "webring"
name = "Random"
url = "https://webring.stavros.io/random"
weight = 2

[[menu.main]]
parent = "webring"
name = "Next"
url = "https://webring.stavros.io/next"
weight = 3

[params.social]
#email = "dzervas@dzervas.gr"
#twitter = "https://twitter.com/_dzervas"
github = "https://github.com/dzervas/whynot.fail"
rss = true

[params.social.utterances]
repo = "dzervas/whynot.fail"

[params.writers]
[params.writers.dzervas]
link = "https://dzervas.gr"
email = "dzervas@dzervas.gr"
bio = "Creator of this site and lover of fails."
twitter = "https://twitter.com/_dzervas"
github = "https://github.com/dzervas"
