name: Hugo Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup NPM
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm ci

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true

      - name: Build site
        run: hugo --minify --gc

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
